---
deployment:
  tasks:
    - export DEPLOYPATH=/home/healthit/public_html/webdev/passphrase 
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp collider.js $DEPLOYPATH
    - /bin/cp common.js $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp passlogo.png $DEPLOYPATH
    - /bin/cp passphrase-background-grey.png $DEPLOYPATH
    - /bin/cp passphrase-background.png $DEPLOYPATH